#!/usr/bin/env python3
"""
Agent Interpretation Injector
Allows the executing agent (Claude) to inject AI-generated interpretations directly
into the workflow without API calls.

When the agent orchestrates the workflow, it can generate interpretations
directly and inject them here.
"""

from typing import Dict, Optional

# Storage for agent-generated interpretations
_agent_interpretations = {}


def set_agent_interpretation(key: str, interpretation: str):
    """
    Set an interpretation generated by the agent
    
    Args:
        key: Unique key for the interpretation (e.g., 'valuation_GOOGL', 'technical_GOOGL')
        interpretation: The AI-generated interpretation text
    """
    _agent_interpretations[key] = interpretation


def get_agent_interpretation(key: str) -> Optional[str]:
    """
    Get an agent-generated interpretation if available
    
    Args:
        key: Unique key for the interpretation
        
    Returns:
        Interpretation text if available, None otherwise
    """
    return _agent_interpretations.get(key)


def clear_agent_interpretations():
    """Clear all stored agent interpretations"""
    _agent_interpretations.clear()


def generate_valuation_key(symbol: str, pe_ratio: float) -> str:
    """Generate unique key for valuation interpretation"""
    return f"valuation_{symbol}_{pe_ratio:.2f}"


def generate_technical_key(symbol: str) -> str:
    """Generate unique key for technical interpretation"""
    return f"technical_{symbol}"


def generate_thesis_key(symbol: str) -> str:
    """Generate unique key for investment thesis"""
    return f"thesis_{symbol}"



